[package]
name = "nerpa_controller"
version = "0.1.0"
authors = ["Debnil Sur <dsur@vmware.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
differential_datalog = {path = "../nerpa_controlplane/nerpa_ddlog/differential_datalog"}
nerpa = {path = "../nerpa_controlplane/nerpa_ddlog"}
types = {path = "../nerpa_controlplane/nerpa_ddlog/types"}

